version: '3.2'
services:
  web:
    build: .
    ports:
      - "3001:3001"  # host:container
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - DATABASE_URL=postgres://ror:1234@db:5432/docker_test
    env_file:
      - db.env
      - rails.env
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
    restart: always

  db:
    image: postgres:9.6
    ports:
      - "5466:5432"
    environment:
      - POSTGRES_USER=ror
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=docker_test
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
  bundle_cache:
