development:
  secret_key_base: "a_secure_dummy_key_for_development_only_1234567890"

test:
  secret_key_base: "another_dummy_key_for_test_env"

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
